redis:
  Addr: localhost:6379
  Password: ""
  DB: 0


mysql:
  Url: root:123456@/taskflow?charset=utf8mb4&parseTime=True&loc=Local


web:
  ReadTimeout: 10
  WriteTimeout: 10
  HttPort: 8008
  RunMode: dsebug